# Generated by Django 4.2 on 2023-04-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNick',
        ),
    ]
