# Generated by Django 4.2 on 2023-04-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100, verbose_name='Название')),
                ('original_title', models.CharField(blank=True, default='', max_length=100, verbose_name='Оригинальное название')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films_app.category', verbose_name='Жанр')),
            ],
        ),
    ]
