# Generated by Django 4.2 on 2023-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='URL'),
        ),
    ]
