# Generated by Django 4.2 on 2023-04-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0004_alter_category_slug_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(default='', verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
