# Generated by Django 4.2 on 2023-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0005_movie_description_movie_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(db_index=True, to='films_app.category', verbose_name='Жанр'),
        ),
    ]
