# Generated by Django 4.2 on 2023-04-25 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films_app', '0007_alter_movie_description_alter_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovies',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films_app.movie', verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='usermovies',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
