# Generated by Django 4.2 on 2023-04-26 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0008_alter_usermovies_movie_id_alter_usermovies_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovies',
            name='category_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='films_app.category', verbose_name='Категории фильма'),
            preserve_default=False,
        ),
    ]
