# Generated by Django 4.2 on 2023-04-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0009_usermovies_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovies',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films_app.category', verbose_name='Категории фильма'),
        ),
    ]
