# Generated by Django 4.2 on 2023-04-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0010_alter_usermovies_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovies',
            name='category_id',
        ),
        migrations.AddField(
            model_name='usermovies',
            name='category_id',
            field=models.ManyToManyField(db_index=True, to='films_app.category', verbose_name='Категории'),
        ),
    ]
