# Generated by Django 4.2 on 2023-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0011_remove_usermovies_category_id_usermovies_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermovies',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(db_index=True, to='films_app.category', verbose_name='Категории'),
        ),
    ]
